### ISSUE TITLE
关于flutter_aliplayer打包报错

### ISSUE THREAD

**Issue by Sandsculpturenetizens** [QiSky/flutter_aliplayer#1]
flutter\.pub-cache\hosted\pub.flutter-io.cn\flutter_aliplayer-5.4.2\android\src\main\java\com\alibaba\fplayer\flutter_aliplayer\FlutterPlayerBase.java:241: ����: <����com.alibaba.fplayer.flutter_aliplayer.FlutterPlayerBase$10>���ǳ����, ����δ����OnSubtitleDisplayListener�еĳ��󷽷�onSubtitleHeader(int,String)
        player.setOnSubtitleDisplayListener(new IPlayer.OnSubtitleDisplayListener() {
                                                                                    ^
ע: ĳЩ�����ļ�ʹ�û򸲸����ѹ�ʱ�� API��
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
ע: ĳЩ�����ļ�ʹ����δ�����򲻰�ȫ�Ĳ�����
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:unchecked ���±��롣
1 ������

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_aliplayer:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
Exception: Gradle task assembleDebug failed with exit code 1

希望大佬解答下

**Comment by QiSky** [comment]
@Sandsculpturenetizens 你用的是sdk版本大于2.0的吗

**Comment by Sandsculpturenetizens** [comment]
> @Sandsculpturenetizens你用的是sdk版本大于2.0的吗

当前 Flutter 2.5.3 Dart 2.14.4，求解

**Comment by QiSky** [comment]
稍等，正在兼容flutter v2版本

**Comment by Sandsculpturenetizens** [comment]
> 稍等，正在兼容flutter v2版本

flutter_aliplayer: ^5.4.2 我看pub上的好像支持2.0吧~

**Comment by QiSky** [comment]
@Sandsculpturenetizens pub.dev上的flutter_aliplayer库作者不是我。。。
